### PR TITLE
[Matrix] change to new C++ PVR interface way

### PR DESCRIPTION
**Pull request by AlwinEsch**
Changes related to xbmc/xbmc#16485.

This make the addon to the new C++ addon interface.

Runtime test with missing backend not performed.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
@ksooo how we do for here with Jenkins?
There are currently no git rights set for them and to bring in without any build not good for me.

**Comment by ksooo** [comment]
@AlwinEsch No idea, I'm not a Jenkins expert. Tell me what needs to be done and I will happy to help.

**Comment by AlwinEsch** [comment]
ping @lrusak, what exactly is need to set for Jenkins on repo rights?

**Comment by lrusak** [comment]
```
  Error while processing pull request 43

  Reason: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/DigitalDevices/pvr.octonet/collaborators/AlwinEsch/permission {"message":"Must have push access to view collaborator permission.","documentation_url":"https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level"}
```

I assume that @AlwinEsch needs push/write rights to this repo

**Pull request merged**
