### PR TITLE
change to automatic depends set on addon.xml

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to kodi Pull Request xbmc/xbmc#12029 and xbmc/xbmc#12109

Not merge in before is in Kodi!

### CODE REVIEW

**Comment by julianscheel** [comment]
@AlwinEsch would you mind to open such pull requests only after the core change was merged? This way I would not need to check for the relating pull request over and over.
Thanks

**Comment by AlwinEsch** [comment]
Is in Kodi now, was only opened on all addons short before to make the time for changes to them so short as possible.

**Comment by AlwinEsch** [comment]
Changes are now in Kodi.

**Comment by Rechi** [comment]
@julianscheel this can be merged now

**Pull request merged**
